#ifndef ENUMDEF_H
#define ENUMDEF_H

//entities
enum {ENTITY_PLAYER, ENTITY_EXPLOSION, ENTITY_ENEMY, ENTITY_PROJECTILE};

//game states
enum {STATE_START, STATE_GAME, STATE_PAUSED, STATE_OVER};

#endif
